#theme: jekyll-theme-cayman
remote_theme: just-the-docs/just-the-docs
logo: "logo.min.png"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      nav_order: 1
