#theme: jekyll-theme-cayman
remote_theme: just-the-docs/just-the-docs
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      nav_order: 1
      has_children: false
      has_toc: false
