dir test\cases\*.html > test\cases\list.txt /b
@echo // This file is automatically generated >test\cases.js
@echo var cases = [ >>test\cases.js
for /F "tokens=1,* delims=. " %%A in (test\cases\list.txt) do @echo '%%A', >>test\cases.js
@echo ]; >>test\cases.js
del test\cases\list.txt
rem type test\cases.js

start "" "http://localhost/test/test.html"
